The task has done
NekitCool1/book-shop pull request #3
Opened 2024-07-10 13:31 UTC by NekitCool1

2024-07-10 17:01 UTC, Elena-Bruyako requested changes
see pr

2024-07-10 17:01 UTC, Elena-Bruyako commented on src/main/java/book/shop/dto/BookDto.java
> +
```suggestion
```

2024-07-10 17:01 UTC, Elena-Bruyako commented on src/main/java/book/shop/dto/CreateBookRequestDto.java
> +
```suggestion
```

2024-07-10 17:01 UTC, Elena-Bruyako commented on src/main/java/book/shop/service/impl/BookServiceImpl.java
> +        book.setIsbn("XXX" + new Random().nextInt());
it's better to remove for now, in future tasks you can add validation pattern or generaye isbn method

2024-07-11 11:02 UTC, MentorMateAcademy requested changes

2024-07-11 11:02 UTC, MentorMateAcademy commented on src/main/java/book/shop/dto/BookDto.java
> +}
clear empty lines between

2024-07-12 06:11 UTC, Elena-Bruyako requested changes
see pr

2024-07-12 06:11 UTC, Elena-Bruyako commented on src/main/java/book/shop/dto/CreateBookRequestDto.java
> +
not fixed

2024-07-12 06:11 UTC, Elena-Bruyako commented on src/main/java/book/shop/repository/impl/BookRepositoryImpl.java
> +            throw new EntityNotFoundException("Can't find the book with id: " + id);
```suggestion
            throw new DataProcessingException("Can't find the book with id: " + id);
```

2024-07-12 06:11 UTC, Elena-Bruyako commented on src/main/java/book/shop/repository/impl/BookRepositoryImpl.java
> +            throw new EntityNotFoundException("Can't ger all books from DB " + e);
```suggestion
            throw new DataProcessingException("Can't get all books from DB " + e);
```

2024-07-14 09:00 UTC, Elena-Bruyako requested changes
see comment

2024-07-14 09:00 UTC, Elena-Bruyako commented on src/main/java/book/shop/dto/CreateBookRequestDto.java
> +
Remove empty line after class declaration
Also, remove empty lines between fields

2024-07-16 06:42 UTC, Elena-Bruyako approved these changes
good job

2024-07-16 09:46 UTC, merged