Solution of spring boot data jpa task
NekitCool1/book-shop pull request #4
Opened 2024-07-13 20:43 UTC by NekitCool1

2024-07-14 09:04 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution

2024-07-14 09:04 UTC, Elena-Bruyako commented on src/main/java/book/shop/model/Book.java
> +@Where(clause = "is_deleted=false")
Use `@SQLRestriction` instead of deprecated `@Where`

2024-07-14 09:04 UTC, Elena-Bruyako commented on src/main/java/book/shop/service/impl/BookServiceImpl.java
> +        return bookRepository.updateBookById(id);
```suggestion
        Book book = bookRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException.......
        bookMapper.updateBookFromDto(bookDto, book);
        return bookMapper.toDto(bookRepository.save(book));
```

Create updateBookFromDto in BookMapper

2024-07-14 09:04 UTC, Elena-Bruyako commented on src/main/java/book/shop/repository/BookRepository.java
> +    BookDto updateBookById(Long id);
remove

2024-07-18 14:42 UTC, MentorMateAcademy requested changes

2024-07-18 14:42 UTC, MentorMateAcademy commented on src/main/java/book/shop/repository/BookRepository.java
> +@Repository
```suggestion
```

2024-07-18 14:42 UTC, MentorMateAcademy commented on src/main/java/book/shop/service/impl/BookServiceImpl.java
> +        book.setIsbn(String.valueOf(new Random().nextInt(1000)));
why do you generate isbn?

2024-07-18 14:43 UTC, MentorMateAcademy commented
![image](https://github.com/user-attachments/assets/89c81b22-8213-4a23-9ac5-5da84b731c19)
fix your conflicts

2024-07-18 19:32 UTC, Elena-Bruyako requested changes
Fix conflicts in your branch

2024-07-18 19:32 UTC, Elena-Bruyako commented on src/main/java/book/shop/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping("/books")
```

2024-07-18 20:54 UTC, merged