Solution of criteria query
NekitCool1/book-shop pull request #5
Opened 2024-07-17 13:39 UTC by NekitCool1

2024-07-21 15:00 UTC, MentorMateAcademy requested changes

2024-07-21 15:00 UTC, MentorMateAcademy commented on src/main/java/book/shop/dto/BookDto.java
> +}
you can use record in this casse

2024-07-21 15:00 UTC, MentorMateAcademy commented on src/main/java/book/shop/repository/book/AuthorSpecificationProvider.java
> +        return "author";
save to constant and reuse it

2024-07-21 15:00 UTC, MentorMateAcademy commented on src/main/java/book/shop/repository/book/BookRepository.java
> +@Repository
```suggestion
```

2024-07-21 15:00 UTC, MentorMateAcademy commented on src/main/java/book/shop/repository/book/TitleSpecificationProvider.java
> +        return "title";
the same

2024-07-21 15:00 UTC, MentorMateAcademy commented on src/main/java/book/shop/service/impl/BookServiceImpl.java
> +        book.setIsbn(String.valueOf(new Random().nextInt(1000)));
why do you create ISBN by yourself?

2024-07-21 15:00 UTC, MentorMateAcademy commented on src/main/java/book/shop/service/impl/BookServiceImpl.java
> +
```suggestion
```

2024-07-24 17:40 UTC, okuzan requested changes

2024-07-24 17:40 UTC, okuzan commented on src/main/java/book/shop/repository/book/AuthorSpecificationProvider.java
> +    private static final String key = "author";
```suggestion
    private static final String KEY = "author";
```

2024-07-24 17:40 UTC, okuzan commented on src/main/java/book/shop/repository/book/AuthorSpecificationProvider.java
> +        return (root, query, criteriaBuilder) -> root.get("author")
```suggestion
        return (root, query, criteriaBuilder) -> root.get(KEY)
```

2024-07-24 17:40 UTC, okuzan commented on src/main/java/book/shop/repository/book/BookSpecificationBuilder.java
> +    private static final String keyForAuthor = "author";
constants should be uppercased

2024-07-24 17:40 UTC, okuzan commented on src/main/java/book/shop/repository/book/BookSpecificationProviderManager.java
> +                .orElseThrow(() -> new EntityNotFoundException(
not a mistake, but since it's not entity, better use NoSuchElementException

2024-07-24 17:40 UTC, okuzan commented on src/main/java/book/shop/repository/book/BookSpecificationProviderManager.java
> +                .filter(b -> b.getKey().equals(key))
replace short naming with an informative one

2024-07-24 17:40 UTC, okuzan commented on src/main/java/book/shop/repository/book/TitleSpecificationProvider.java
> +        return (root, query, criteriaBuilder) -> root.get("title")
same (constant)

2024-07-24 19:25 UTC, closed without merging